apiVersion: v1
kind: Service
metadata:
  name: neo4j-server
spec:
  selector:
    app: neo4j-server
  ports:
    -  protocol: TCP
       port: 7474
       targetPort: 7474
    -  protocol: TCP
       port: 7473
       targetPort: 7473
    -  protocol: TCP
       port: 7687
       targetPort: 7687