apiVersion: v1
kind: Service
metadata:
  name: neo4j-server
spec:
  selector:
    app: neo4j-server
  type: LoadBalancer
  ports:
    -  protocol: TCP
       port: 7474
       targetPort: 7474
       name: web
    -  protocol: TCP
       port: 7473
       targetPort: 7473
       name: server
    -  protocol: TCP
       port: 7687
       targetPort: 7687
       name: bolt