server:
  port: 8090
zuul:
  routes:
    pathway:
      path: /api/pathway/**
      url: http://localhost:8081/
      stripPrefix: true
    structure:
      path: /api/structure/**
      url: http://localhost:8088/
      stripPrefix: true
    reference:
      path: /api/genome/**
      url: http://localhost:8080/
      stripPrefix: true
    reactome:
      path: /api/reactome/**
      url: https://reactome.org/
      stripPrefix: true
    datasets:
      path: /api/datasets/**
      url: http://www.biodalliance.org/
