apiVersion: v1
kind: Service
metadata:
  name: microbrewery-gateway
spec:
  selector:
    app: microbrewery-gateway
  type: LoadBalancer
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 8090
