apiVersion: apps/v1
kind: Deployment
metadata:
  name: genomics
  labels:
    app: genomics
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genomics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: genomics
    spec:
      serviceAccountName: spark
      containers:
        - image: 465129930157.dkr.ecr.eu-west-1.amazonaws.com/microbrewery-genomics:0.1
          imagePullPolicy: Always
          name: genomics
          command: ["tail","-f","/dev/null"]
          ports:
            - containerPort: 8087
              protocol: TCP
          volumeMounts:
            - name: efs-pvc
              mountPath: "/mnt/efs"
          env:
            - name: GENOME_NAME
              value: "S288C"
            - name: GENOME_FILE
              value: "/mnt/efs/S288C_reference_genome_R64-2-1_20150113/saccharomyces_cerevisiae_R64-2-1_20150113.gff"
      volumes:
      - name: efs-pvc
        persistentVolumeClaim:
          claimName: efs
          
