apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-server-maintenance
  labels:
    app: neo4j-server-maintenance
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-server-maintenance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: neo4j-server-maintenance
    spec:
      containers:
        - image: neo4j:latest
          imagePullPolicy: Always
          name: neo4j-server-maintenance
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
      volumes:
        - name: neo4j-data
          awsElasticBlockStore:
            volumeID: vol-0768d8a4bf4ac3670