<<<<<<< HEAD
# Default values for microbrewery-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
=======
images:
  gateway: 465129930157.dkr.ecr.eu-west-1.amazonaws.com/microbrewery-gateway:1.0-SNAPSHOT
  structure: 465129930157.dkr.ecr.eu-west-1.amazonaws.com/microbrewery-structure:1.0-SNAPSHOT
  cytoscape-menu: 465129930157.dkr.ecr.eu-west-1.amazonaws.com/microbrewery-cytoscape-menu:1.0-SNAPSHOT
  neo4j-server: neo4j:latest
ports:
  gateway: 8090
  structure: 8088
  cytoscape-menu: 8089
url:
  structure: http://microbrewery-structure.default.svc.cluster.local/
  cytoscape-menu: http://microbrewery-cytoscape-menu.default.svc.cluster.local/
  neo4j-server: http://neo4j-server.default.svc.cluster.local/
volumes:
  neo4j-data:
    id: vol-0768d8a4bf4ac3670
>>>>>>> 20417f34df22c10ab7533ace0a2050287d499d61
