apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbrewery-gateway
  labels:
    app: microbrewery-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microbrewery-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microbrewery-gateway
    spec:
      containers:
        - image: {{ .Values.images.gateway }}
          imagePullPolicy: Always
          name: microbrewery-gateway
          ports:
            - containerPort: {{ .Values.images.port }}
              protocol: TCP
          env:
            - name: STRUCTURE_URL
              value: {{ Values.url.structure }}
            - name: CYTOSCAPE_MENU_URL
              value: {{ Values.url.cytoscape-menu }}

