apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbrewery-gateway
  labels:
    app: microbrewery-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microbrewery-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microbrewery-gateway
    spec:
      containers:
        - image: 465129930157.dkr.ecr.eu-west-1.amazonaws.com/microbrewery-gateway:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: microbrewery-gateway
          ports:
            - containerPort: 8090
              protocol: TCP
          env:
            - name: STRUCTURE_URL
              value: "http://microbrewery-structure.default.svc.cluster.local"
            - name: NEO4J_URL
              value: "http://microbrewery-cytoscape-menu.default.svc.cluster.local/"

