apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-server
  labels:
    app: neo4j-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: neo4j-server
    spec:
      containers:
        - image: {{ .Values.images.neo4j_server }}
          imagePullPolicy: Always
          name: neo4j-server
          ports:
            - containerPort: 7474
              protocol: TCP
            - containerPort: 7473
              protocol: TCP
            - containerPort: 7687
              protocol: TCP
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
      volumes:
        - name: neo4j-data
          awsElasticBlockStore:
            volumeID: {{ .Values.volumes.neo4j_data.id }}