apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbrewery-structure
  labels:
    app: microbrewery-structure
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microbrewery-structure
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microbrewery-structure
    spec:
      containers:
        - image: {{ .Values.images.structure }}
          imagePullPolicy: Always
          name: microbrewery-structure
          ports:
            - containerPort: {{ .Values.port.structure }}
              protocol: TCP
