apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbrewery-structure
  labels:
    app: microbrewery-structure
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microbrewery-structure
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microbrewery-structure
    spec:
      containers:
<<<<<<< HEAD:deployment/helm-microbrewery/templates/deployment/structure.yaml
        - image: 465129930157.dkr.ecr.eu-west-1.amazonaws.com/microbrewery-structure:1.0-SNAPSHOT
=======
        - image: {{ .Values.images.structure }}
>>>>>>> 20417f34df22c10ab7533ace0a2050287d499d61:deployment/helm-microbrewery/templates/deployment/structure.yaml
          imagePullPolicy: Always
          name: microbrewery-structure
          ports:
            - containerPort: {{ .Values.port.structure }}
              protocol: TCP
          env:
            - name: NEO4J_SERVER_HOST
              value: "neo4j-server.default.svc.cluster.local"